[package]
name = "sheet_excavator"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "sheet_excavator"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.81"
calamine = "0.24.0"
futures = "0.3.30"
pyo3 = "0.20.0"
serde_json = "1.0.115"
tokio = {version = "1.37.0", features = ["full"] }
